version: "3.9"

services:
  backend:
    build: ./backend
    container_name: enterprise-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: enterprise-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
